version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: truehome_local_django
    depends_on:
      - postgres
    volumes:
      - .:/code
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: truehome_production_postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  vue:
    build:
      context: .
      dockerfile: ./compose/local/vue/Dockerfile
    image: truehome_local_vue
    depends_on:
      - django
    volumes:
      - ./frontend:/app/:ro
      - /app/node_modules
    ports:
      - "8080:8080"
